Q1 LinearRegression

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings("ignore")

In [65]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\ford_car_dataset.csv")

In [66]:
df.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [67]:
df.shape

(17966, 9)

In [68]:
df.columns

Index(['model', 'year', 'price', 'transmission', 'mileage', 'fuelType', 'tax',
       'mpg', 'engineSize'],
      dtype='str')

In [69]:
df = df.dropna()

In [70]:
df.info()

<class 'pandas.DataFrame'>
Index: 17941 entries, 0 to 17965
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         17941 non-null  str
 1   year          17941 non-null  int64
 2   price         17941 non-null  int64
 3   transmission  17941 non-null  str
 4   mileage       17941 non-null  int64
 5   fuelType      17941 non-null  str
 6   tax           17941 non-null  int64
 7   mpg           17941 non-null  float64
 8   engineSize    17941 non-null  float64
dtypes: float64(2), int64(4), str(3)
memory usage: 1.7 MB

In [71]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [72]:
df = pd.get_dummies(df, drop_first=True)
print("One-Hot Encoding Completed Successfully")

One-Hot Encoding Completed Successfully

In [73]:
X = df.drop("price", axis=1)
y = df["price"]

In [74]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("train_test_split Complete Successfully")
X_train

train_test_split Complete Successfully

,year,mileage,tax,mpg,engineSize,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,model_ Fiesta,...,model_ Tourneo Connect,model_ Tourneo Custom,model_ Transit Tourneo,model_Focus,transmission_Manual,transmission_Semi-Auto,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
1024,2014,8487,30,54.3,1.2,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
15975,2018,13724,145,49.6,1.0,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
12678,2019,8905,145,55.4,1.0,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
6229,2018,26915,145,58.9,1.5,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
4352,2019,6453,145,53.3,1.0,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11302,2019,6880,145,60.1,1.0,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
11982,2018,28528,145,65.7,1.0,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
5404,2017,27107,145,65.7,1.0,False,False,False,False,True,...,False,False,False,False,True,False,False,False,False,True
861,2017,35850,20,61.4,1.0,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
15819,2016,5313,160,45.6,1.5,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True

In [75]:
df = pd.get_dummies(df, drop_first=True)
X = df.drop("price", axis=1)
y = df["price"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [76]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
y_test = scaler.transform(X_test)
print("StandardScaler Applied Successfully")

StandardScaler Applied Successfully

In [77]:
X_train

array([[-1.41211713, -0.76456109, -1.33582792, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 0.55901668, -0.49583272,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 1.05180013, -0.74311208,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       ...,
       [ 0.06623323,  0.19089476,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 0.06623323,  0.63952798, -1.49619471, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [-0.42655022, -0.92742988,  0.74894042, ..., -0.03443702,
        -0.00834755,  0.69219229]], shape=(14352, 34))

In [78]:
model = LinearRegression()
print("Linear Regression Model Trained Successfully")
model.fit(X_train, y_train)

Linear Regression Model Trained Successfully

LinearRegression()

In [79]:
y_pred = model.predict(X_test)
print("Prediction Completed Successfully")
y_pred

Prediction Completed Successfully

array([  1730763.42591157, -56751182.09694923,  -5541673.72702319, ...,
       -30855532.78569977, -14766079.57438172, -35763242.17145484],
      shape=(3589,))

In [84]:
score = r2_score(y_test, y_pred)
print("R2 Score:", score)

R2 Score: 0.82248331731935

In [87]:
result = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})
print(result)

      Actual Price  Predicted Price
0            10099     12044.867349
1             1990     -2457.908808
2            14700     14235.891292
3            11899     10313.082208
4            10400     11620.938113
...            ...              ...
3584         11999     13253.689267
3585         10998     10537.910955
3586          8999     11728.829165
3587         15475     15127.783599
3588          9498     12662.990920

[3589 rows x 2 columns]

In [88]:
import joblib
joblib.dump(model, "Price_model.pkl")
joblib.dump(scaler, "Price_scaler.pkl")
joblib.dump(X.columns, "Price_columns.pkl")

print("All Files Saved Successfully")

All Files Saved Successfully

Q2 LogisticRegreesion

In [89]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
import warnings
warnings.filterwarnings("ignore")

In [91]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\heart.csv")

In [92]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [93]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='str')

In [94]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      917 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 97.7 KB

In [95]:
df.shape

(918, 12)

In [96]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        1
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [97]:
df = df.dropna()
print("Missing Values Removed Successfully")

Missing Values Removed Successfully

In [99]:
df = pd.get_dummies(
    df, 
    drop_first=True,
    dtype=int
)
df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1

In [100]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0.0,1,0,1,0,1,0,0,0,1

In [101]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X = scaler.transform(X_test)
print("StandardScaler Applied Successfully")
X_train

StandardScaler Applied Successfully

array([[-1.41211713, -0.76456109, -1.33582792, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 0.55901668, -0.49583272,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 1.05180013, -0.74311208,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       ...,
       [ 0.06623323,  0.19089476,  0.50839023, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [ 0.06623323,  0.63952798, -1.49619471, ..., -0.03443702,
        -0.00834755,  0.69219229],
       [-0.42655022, -0.92742988,  0.74894042, ..., -0.03443702,
        -0.00834755,  0.69219229]], shape=(14352, 34))

In [107]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("train_test_split Complete Successfully")
X_train

train_test_split Complete Successfully

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
795,42,120,240,1,194,0.8,1,0,1,0,1,0,0,0,0
25,36,130,209,0,178,0.0,1,0,1,0,1,0,0,0,1
84,56,150,213,1,125,1.0,1,0,0,0,1,0,1,1,0
10,37,130,211,0,142,0.0,0,0,1,0,1,0,0,0,1
344,51,120,0,1,104,0.0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,48,120,254,0,110,0.0,0,0,0,0,0,1,0,0,1
270,45,120,225,0,140,0.0,1,0,0,0,1,0,0,0,1
861,65,110,248,0,158,0.6,1,0,0,0,0,0,0,0,1
435,60,152,0,0,118,0.0,1,0,0,0,0,1,1,0,1
102,40,150,392,0,130,2.0,0,0,0,0,1,0,0,1,0

In [108]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [109]:
y_pred = model.predict(X_test)
print("Prediction Completed Successfully")
y_pred

Prediction Completed Successfully

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1])

In [112]:
cm = confusion_matrix(y_test, y_pred)
print("confusion Matrix")
print(cm)

confusion Matrix
[[65  8]
 [14 97]]

In [113]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy", acc)

Accuracy 0.8804347826086957

In [114]:
pre = precision_score(y_test, y_pred)
print("precision score:", pre)

precision score: 0.9238095238095239

In [115]:
rec = recall_score(y_test, y_pred)
print("Recall:", rec)

Recall: 0.8738738738738738

In [116]:
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.8981481481481481

Q3 K-Nearest Neighbors

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings("ignore")

In [121]:
df = pd. read_csv(r"C:\Users\DELL\Downloads\heart.csv")
print("DataSet Load Successfully")

DataSet Load Successfully

In [122]:
df = pd.get_dummies(
    df,
    drop_first=True,
    dtype=int 
)
print("Encoding Complete Successfully")
df.head()

Encoding Complete Successfully

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1

In [123]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [124]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
X_test

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
668,63,140,195,0,179,0.0,0,1,0,0,1,0,0,0,1
30,53,145,518,0,130,0.0,1,0,1,0,1,0,0,1,0
377,65,160,0,1,122,1.2,1,0,0,0,0,1,0,1,0
535,56,130,0,0,122,1.0,1,0,0,0,0,0,1,1,0
807,54,108,309,0,156,0.0,1,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,50,140,288,0,140,0.0,0,0,1,0,1,0,1,1,0
745,63,108,269,0,169,1.8,0,0,0,0,1,0,1,1,0
584,64,141,244,1,116,1.5,1,0,0,0,0,1,1,1,0
878,49,130,266,0,171,0.6,1,1,0,0,1,0,0,0,1
451,64,144,0,0,122,1.0,1,0,0,0,0,1,1,1,0

In [125]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-1.24506731, -0.70898547,  0.372803  , ..., -0.83846064,
        -1.03325003, -0.84792072],
       [-1.8862362 , -0.16628515,  0.08614581, ..., -0.83846064,
        -1.03325003,  1.17935554],
       [ 0.25099346,  0.91911549,  0.12313384, ...,  1.19266183,
         0.96781995, -0.84792072],
       ...,
       [ 0.67843939, -0.16628515,  0.49301407, ...,  1.19266183,
        -1.03325003,  1.17935554],
       [ 0.67843939,  1.02765555, -1.84647842, ...,  1.19266183,
        -1.03325003,  1.17935554],
       [-1.45879027,  0.91911549,  1.77834789, ..., -0.83846064,
         0.96781995, -0.84792072]], shape=(734, 15))

In [127]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [128]:
y_pred = knn.predict(X_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1])

In [129]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy for k=5:", acc)

Accuracy for k=5: 0.8532608695652174

In [134]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy for k=7:", acc)

Accuracy for k=7: 0.8967391304347826

In [135]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy for k=9:", acc)

Accuracy for k=9: 0.8858695652173914

In [136]:
result = {}
for k in [5, 7, 9]:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    result[k] = accuracy_score(y_test, pred)

print("Accuracy Comparison")
for k, acc in result.items():
    print(f"k = (k) - Accuracy = {acc:.4f}")

best_k = max(result, key=result.get)
print("\nBest k =", best_k)
print("Best Accuracy =", result[best_k])

Accuracy Comparison
k = (k) - Accuracy = 0.8533
k = (k) - Accuracy = 0.8967
k = (k) - Accuracy = 0.8859

Best k = 7
Best Accuracy = 0.8967391304347826

Q4 Naive Bayes

In [137]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings("ignore")

In [138]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\heart.csv")

In [139]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [140]:
df = pd.get_dummies(
    df,
    drop_first=True,
    dtype=int
)
df.tail()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
913,45,110,264,0,132,1.2,1,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,1,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0.0,0,1,0,1,0,1,0,0,0,1

In [142]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0.0,1,0,1,0,1,0,0,0,1

In [143]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("train_test_split Complete Successfully")
X_train

train_test_split Complete Successfully

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
795,42,120,240,1,194,0.8,1,0,1,0,1,0,0,0,0
25,36,130,209,0,178,0.0,1,0,1,0,1,0,0,0,1
84,56,150,213,1,125,1.0,1,0,0,0,1,0,1,1,0
10,37,130,211,0,142,0.0,0,0,1,0,1,0,0,0,1
344,51,120,0,1,104,0.0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,48,120,254,0,110,0.0,0,0,0,0,0,1,0,0,1
270,45,120,225,0,140,0.0,1,0,0,0,1,0,0,0,1
860,60,130,253,0,144,1.4,1,0,0,0,1,0,1,0,1
435,60,152,0,0,118,0.0,1,0,0,0,0,1,1,0,1
102,40,150,392,0,130,2.0,0,0,0,0,1,0,0,1,0

In [144]:
sca = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("StandardScaler Applied Successfully")
X_train

StandardScaler Applied Successfully

array([[-1.24506731, -0.70898547,  0.372803  , ..., -0.83846064,
        -1.03325003, -0.84792072],
       [-1.8862362 , -0.16628515,  0.08614581, ..., -0.83846064,
        -1.03325003,  1.17935554],
       [ 0.25099346,  0.91911549,  0.12313384, ...,  1.19266183,
         0.96781995, -0.84792072],
       ...,
       [ 0.67843939, -0.16628515,  0.49301407, ...,  1.19266183,
        -1.03325003,  1.17935554],
       [ 0.67843939,  1.02765555, -1.84647842, ...,  1.19266183,
        -1.03325003,  1.17935554],
       [-1.45879027,  0.91911549,  1.77834789, ..., -0.83846064,
         0.96781995, -0.84792072]], shape=(734, 15))

In [145]:
model = GaussianNB()
print("Naive Bayes Model Trained Successfully")
model.fit(X_train, y_train)

Naive Bayes Model Trained Successfully

GaussianNB()

In [146]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1])

In [147]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix")
print(cm)

Confusion matrix
[[68  9]
 [17 90]]

In [148]:
report = classification_report(y_test, y_pred)
print("Classification Report")
print(report)

Classification Report
              precision    recall  f1-score   support

           0       0.80      0.88      0.84        77
           1       0.91      0.84      0.87       107

    accuracy                           0.86       184
   macro avg       0.85      0.86      0.86       184
weighted avg       0.86      0.86      0.86       184

Q5 Algorithm Comparison

In [149]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
import warnings
warnings.filterwarnings("ignore")

In [150]:
df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1

In [151]:
df.isnull()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
914,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
915,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
916,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
917,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [152]:
df = pd.get_dummies(
    df,
    drop_first=True,
    dtype=int
)
df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1

In [154]:
X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [155]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
print("train_test_split Complete Successfully")
X_train

train_test_split Complete Successfully

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
795,42,120,240,1,194,0.8,1,0,1,0,1,0,0,0,0
25,36,130,209,0,178,0.0,1,0,1,0,1,0,0,0,1
84,56,150,213,1,125,1.0,1,0,0,0,1,0,1,1,0
10,37,130,211,0,142,0.0,0,0,1,0,1,0,0,0,1
344,51,120,0,1,104,0.0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,48,120,254,0,110,0.0,0,0,0,0,0,1,0,0,1
270,45,120,225,0,140,0.0,1,0,0,0,1,0,0,0,1
860,60,130,253,0,144,1.4,1,0,0,0,1,0,1,0,1
435,60,152,0,0,118,0.0,1,0,0,0,0,1,1,0,1
102,40,150,392,0,130,2.0,0,0,0,0,1,0,0,1,0

In [156]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("StandardScaler Applied Successfully")
X_test

StandardScaler Applied Successfully

array([[ 0.99902384,  0.37641517, -0.04331227, ..., -0.83846064,
        -1.03325003,  1.17935554],
       [-0.06959099,  0.64776533,  2.94347064, ..., -0.83846064,
         0.96781995, -0.84792072],
       [ 1.2127468 ,  1.46181581, -1.84647842, ..., -0.83846064,
         0.96781995, -0.84792072],
       ...,
       [ 1.10588532,  0.4306852 ,  0.40979102, ...,  1.19266183,
         0.96781995, -0.84792072],
       [-0.49703693, -0.16628515,  0.61322515, ..., -0.83846064,
        -1.03325003,  1.17935554],
       [ 1.10588532,  0.5934953 , -1.84647842, ...,  1.19266183,
         0.96781995, -0.84792072]], shape=(184, 15))

In [157]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Naive Bayes": GaussianNB()
}
result = []
print("All Modules Created Successfully")

All Modules Created Successfully

In [159]:
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    result.append([name, accuracy, precision, recall, f1])
    print("All Modules Trained Successfully")

All Modules Trained Successfully
All Modules Trained Successfully
All Modules Trained Successfully

In [160]:
comparison = pd.DataFrame(
    result,
    columns=[
        "Algorithm",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)
print(comparison)

             Algorithm  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.853261   0.900000  0.841121  0.869565
1                  KNN  0.853261   0.900000  0.841121  0.869565
2          Naive Bayes  0.858696   0.909091  0.841121  0.873786

In [161]:
best = comparison.loc[comparison["Accuracy"].idxmax()]
print("Best Algorithm:", best["Algorithm"])
print("Best Accuracy:", best["Accuracy"])

Best Algorithm: Naive Bayes
Best Accuracy: 0.8586956521739131

In [162]:
import joblib
joblib.dump(models["Logistic Regression"], "Logistic_model.pkl")
joblib.dump(models["KNN"], "knn_model.pkl")
joblib.dump(models["Naive Bayes"], "Naive_bayes_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")
print("All pkl files Saved Successfully")

All pkl files Saved Successfully